### PR TITLE
Fixing deferred task database locking

### LINKED ISSUE #775: SQLite Error 6: 'database table is locked'.
Master branch. Brand new site with SQLite.

After logging in to dashboard, enable and then disable a module, will result in this error.

### PR DESCRIPTION
**Pull request by sebastienros**
- Prevent the deferred task engine from creating a deadlock by disposing the request
services before creating a new one.
- Ref count the requests on a shell context in order to release the shell context only when
all its requests are finished

Fixes #775

### CODE REVIEW

**Comment by sebastienros** [comment]
A potential issue is that when the deferred scope is created, it's done when the context is already released, so the deferred task will be executed on the new updated scope. I need to check if the existing tasks don't actually need to be run before.

File: src/OrchardCore/Orchard.DeferredTasks/DeferredTaskMiddleware.cs [hunk 1]
```diff
@@ -30,16 +30,27 @@ public DeferredTaskMiddleware(RequestDelegate next, IShellHost orchardHost)
...
+                if (deferredTaskEngine != null && deferredTaskEngine.HasPendingTasks)
                 {
-                    var deferredTaskEngine = scope.ServiceProvider.GetService<IDeferredTaskEngine>();
+                    // Dispose the scoped services for the current request, and create a new one
+                    (httpContext.RequestServices as IDisposable).Dispose();
 
-                    if (deferredTaskEngine != null && deferredTaskEngine.HasPendingTasks)
+                    var shellContext = _orchardHost.GetOrCreateShellContext(shellSettings);
+
+                    if (!shellContext.Released)
```
Comment (jtkech) [inline src/OrchardCore/Orchard.DeferredTasks/DeferredTaskMiddleware.cs]: Oh yes, you mean that the newly created shellContext could have been used and released by another request. So, maybe other pending tasks will be executed but on another context.

File: src/OrchardCore/Orchard.Environment.Shell.Abstractions/Builders/ShellContext.cs [hunk 2]
```diff
@@ -27,9 +30,57 @@ public class ShellContext : IDisposable
...
+        }
+
+        public void RequestEnded()
+        {
+            var refCount = Interlocked.Decrement(ref _refCount);
+
+            if (_released && refCount == 0)
+            {
+                Dispose();
+            }
```
Comment (jtkech) [inline src/OrchardCore/Orchard.Environment.Shell.Abstractions/Builders/ShellContext.cs]: I first thought that refCount could be incremented while disposing, but it's not possible because here the shellContext is no more in the shellContext Dictionary and is a candidate to be disposed. So, ok.

**Comment by sebastienros** [comment]
I looked at the code and it should be ok.

**Comment by jtkech** [comment]
I tried it and approved it.

Just one remark, not already checked but do we need to do some changes in other places where a child scope is used.  E.g in `RecipeExecutor.cs` we have.

            // The recipe execution might have invalidated the shell by enabling new features,
            // so the deferred tasks need to run on an updated shell context if necessary.
            shellContext = _orchardHost.GetOrCreateShellContext(_shellSettings);
            using (var scope = shellContext.CreateServiceScope())
            {
                var deferredTaskEngine = scope.ServiceProvider.GetService<IDeferredTaskEngine>();

                // The recipe might have added some deferred tasks to process
                if (deferredTaskEngine != null && deferredTaskEngine.HasPendingTasks)
                {
                    var taskContext = new DeferredTaskContext(scope.ServiceProvider);
                    await deferredTaskEngine.ExecuteTasksAsync(taskContext);
                }
            }

**Comment by sebastienros** [comment]
No, these are ok because we maintain the recipe executor scope independently from the request.

**Comment by jtkech** [comment]
Ok, i need a little time to think about this last thing.
Otherwise all is ok for me.
Already merged, cool.
